### ISSUE TITLE
The official altium-designer-addons project is now hosted on GitHub!

### ISSUE THREAD

**Issue by justinmassiot** [timytamy/altium-designer-addons#8]
Hi @timytamy,

@PetrTos, the owner/maintainer of the former ["altium-designer-addons" Google Code project](http://code.google.com/p/altium-designer-addons), has now migrated the full repository to GitHub. As a consequence, https://github.com/Altium-Designer-addons/scripts-libraries is the new place where to contribute because the project page at Google Code is no longer in service.

I can see that you have already migrated the project to GitHub by yourself.
To keep the best level of contribution, I encourage you to:
1. Ask @PetrTos to be a contributor of the project, of fork the project,
2. Apply your modifications on that project,
3. Close your own project, and continue to contribute to the official project by committing or forking + submitting pull requests.

Thanks a lot for your cooperation.

**Comment by timytamy** [comment]
Been a while since I looked at this but you are correct, either I didn't see that or it didn't exist when I first did the migration. Will close this.
